version: "3.1"

services:
  # Airflow setup
  airflow:
    image: airflow:2.9.1
    volumes:
      - ./airflow:/opt/airflow
      - ./requirements.txt:/opt/airflow/requirements.txt
    ports:
      - "8081:8080"
    command: airflow standalone

  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./meta/miniodata:/data
    env_file:
      - .env
    networks:
      - data_network
  
  mc:
    image: minio/mc
    container_name: mc
    hostname: mc
    env_file:
      - .env
    volumes:
      - ./meta/mcdata:/data
    entrypoint: >
      /bin/sh -c " until (/usr/bin/mc config host add minio http://minio:9000/ minio minio123) do echo '...waiting...' && sleep 10; done; /usr/bin/mc mb minio/mlflow; tail -f /dev/null;"
    depends_on:     
      - minio
    networks:
      - data_network
