version: "3.1"

services:
  airflow:
    image: airflow:2.9.1
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8081:8080"
    command: airflow standalone

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: nhanbui
    volumes:
      - ./data/:/data/db/